---
title: "Seed influence"
author: "Suharkov MP"
date: "24 12 2020"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=F, message=F, echo=F}
# Load all required packages (list was taken from https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/advancing-text-mining/)
library(tidyverse)        # Also loads dplyr, ggplot2, and haven
library(quanteda)         # For NLP
#library(readtext)        # To read .txt files
library(stringi)          # corpus analysis
library(stm)              # For structural topic models
library(stminsights)      # For visual exploration of STM
library(wordcloud)        # To generate wordclouds
library(gsl)              # Required for the topicmodels package
library(topicmodels)      # For topicmodels
library(caret)            # For machine learning
library(tm)               #text analisys
```

# Overview

This paper is my attempt to find if there any influence of chosen seed at the word distribution. As before, the en_US locale is used. 

Load the whole data:
```{r data, warning=F, message=F, echo=F}
blogs <- corpus(readLines('./final/en_US/en_US.blogs.txt'))
news <- corpus(readLines('./final/en_US/en_US.news.txt'))
twitter <- corpus(readLines('./final/en_US/en_US.twitter.txt'))
```

Now seeds, I used a method of typing random numbers by keyboard, so they are true-random, not pseudo.
## Seed 362
```{r seed362, warning=F, message=F}
construct_seed <- function(seed) {
  set.seed(seed = seed)
  blogs <- corpus_sample(blogs, size = 5000)
  news <- corpus_sample(news, size = 5000)
  twitter <- corpus_sample(twitter, size = 5000)
  docnames(blogs) <- c(1:5000)
  docnames(news) <- c(5001:10000)
  docnames(twitter) <- c(10001:15000)
  corp <- blogs + news + twitter
  tokens <- tokens(corp)
  #remove numbers and punctuation
  tokens <- tokens(tokens, remove_punct = T, remove_numbers = T)
  #remove stopwords
  tokens <- tokens_select(tokens, pattern = stopwords('en'), selection = 'remove')
  #remove messy symbols
  token <<- tokens
}
#construct_seed(seed = 362)
```
```
## Seed 24734

## Seed 346

## Seed 12354

## Seed 47

## Seed 4754

## Seed 234

## Seed 67

## Seed 780
